[file_operations]
;path_to_csv_folder= .
;search_string=output/20250709_*_790478.csv
;calibration_csv = './calibration.csv'


[injection]
Vo = 12000 ;mL of H20 collected stream
mass_salt = 4000 ;g
bg_start = "16:26:11"#time(16,26,11)
bg_end = "16:29:00"#time(16,27,14)
trial_start = "16:30:00"
trial_end = "16:35:57"
record_end = "16:37:54"

[calibration]
;Vcal = x['Vol_secondary_mL'][0] ;move to utils
;vol_injection_sample = 100 ;ml
;Vnew = Vo +  mass_salt / rho_salt ;move to utils
;vol_solution_injected = Vnew - vol_calibration_sample ;ml, move to utils
;injection_conc = (mass_salt) / (Vo) ;g/ml, move to utils

[constants]
;rho_salt = 2.165 ;density of NaCl in g/cm3
